on:
  push:
    branches:
      - main 

name: 🚀 Deploy React Admin Panel

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📦 Install Node.js and Yarn
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - run: npm install -g yarn

    - name: 📂 Install project dependencies
      run: yarn install

    - name: 🏗️ Build React app
      run: yarn build

    - name: 🚀 Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /admin.navigo.et/
